---
title: "Data_Documentation"
output: html_document
date: "2023-12-08"
editor_options: 
  markdown: 
    wrap: sentence
---

# Data Documentation

## 1. Link for each datasets

-   Healthcare5Years: This is the link for 2022 setting, got each year data then merged (2022 2021 2019 2018 2017)\
    <https://data.census.gov/mdat/#/search?ds=ACSPUMS1Y2022&vv=PERNP&cv=HICOV&rv=ucgid&wt=PWGTP&g=0400000US01,02,04,05,06,08,09,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56>

-   SNAP2022Race\
    <https://data.census.gov/mdat/#/search?ds=ACSPUMS1Y2022&cv=RAC1P,FS&rv=ucgid&wt=WGTP&g=0400000US01,02,04,05,06,08,09,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56>

-   SNAP7Years\
    <https://www.fns.usda.gov/pd/supplemental-nutrition-assistance-program-snap>

-   Red/Blue states\
    <https://www.cnn.com/election/2020/results/president>

## 2. Explanation of all variables

-   State: The name of the state
-   Year: The year for which the data is relevant
-   Total(Healthcare): Total number of individuals in the state
-   With health insurance coverage: Number of individuals with public health insurance coverage
-   No health insurance coverage: Number of individuals without public health insurance coverage
-   SNAP Household Participation: The number of households participating in SNAP
-   SNAP Persons Participation: The number of persons participating in SNAP
-   SNAP Total Cost: Total cost of SNAP in the state
-   SNAP Cost Per Household: Average cost of SNAP per participating household
-   SNAP Cost Per Persons: Average cost of SNAP per participating person
-   Total(SNAP-Racebased): Total number of SNAP participants based on race
-   White_alone: Number of SNAP participants who are White alone
-   Black or African American alone: Number of SNAP participants who are Black or African American alone
-   American Indian alone: Number of SNAP participants who are American Indian alone
-   Alaska Native alone: Number of SNAP participants who are Alaska Native alone
-   American Indian and Alaska Native tribes specified; or American Indian or Alaska Native, not specified and no other races: Number of SNAP participants in specified American Indian and Alaska Native tribes, or unspecified American Indian or Alaska Native tribes without other races
-   Asian alone: Number of SNAP participants who are Asian alone
-   Native Hawaiian and Other Pacific Islander alone: Number of SNAP participants who are Native Hawaiian and Other Pacific Islander alone
-   Some other race alone: Number of SNAP participants who are of some other race alone
-   Two or More Races: Number of SNAP participants who belong to two or more races.

## 3. Basic summary statistics

This merged dataset comprises 306 rows and 21 columns.
It contains a total of 255 missing values across all SNAP2022Race variables, due to the exclusive merging of 2022 SNAP Race data.
However, as our objective with the Race variable is to examine the most recent year, which is 2022, these missing values do not compromise the analysis.
Except for the SNAP2022Race variables, all the columns have a valid data.\

```{r echo=FALSE}
library(tidyverse)

SNAP2022Race <- read_delim("../Datasets/SNAP_Race_2022.csv")
SNAP2022Race <- rename(SNAP2022Race, State = `Selected Geographies`)
head(SNAP2022Race,5)

SNAP7Years <- read_delim("../Datasets/SNAP_7years.csv")
head(SNAP7Years,5)

HealthcarePublic <- read_delim("../Datasets/NEWhealthcareDATA.csv")
HealthcarePublic <- rename(HealthcarePublic, State = 'Selected Geographies')

merged_data <- inner_join(HealthcarePublic, SNAP7Years, by = c("State", "Year"))
merged_data <- inner_join(merged_data, SNAP2022Race, by = c("State", "Year"))


head(merged_data,5)

dim(merged_data)

missing_or_invalid_values_count <- merged_data %>%
  summarise_all(~sum(is.na(.) | . == ""))

missing_or_invalid_values_count
write.csv(merged_data, "merged_data.csv", row.names=FALSE)
```
